import type { OptionLeg, TradeIdea } from "@prisma/client";
import type { TradeInput } from "@/lib/risk";

type TradeIdeaWithLegs = TradeIdea & {
  optionLegs?: OptionLeg[];
};

export function tradeIdeaToInput(idea: TradeIdeaWithLegs): TradeInput {
  return {
    symbol: idea.symbol,
    direction: idea.direction,
    strategy: idea.strategy,
    thesis: idea.thesis,
    catalyst: idea.catalyst,
    invalidationLevel: idea.invalidationLevel,
    expirationDate: idea.expirationDate,
    optionContractSymbol: idea.optionContractSymbol,
    optionType: idea.optionType,
    strikePrice: idea.strikePrice,
    shortStrikePrice: idea.shortStrikePrice,
    contractBid: idea.contractBid,
    contractAsk: idea.contractAsk,
    contractMid: idea.contractMid,
    contractDelta: idea.contractDelta,
    contractGamma: idea.contractGamma,
    contractTheta: idea.contractTheta,
    contractVega: idea.contractVega,
    contractRho: idea.contractRho,
    contractImpliedVolatility: idea.contractImpliedVolatility,
    contractUnderlyingPrice: idea.contractUnderlyingPrice,
    contractBreakEvenPrice: idea.contractBreakEvenPrice,
    contractSnapshotAt: idea.contractSnapshotAt,
    premiumCost: idea.premiumCost,
    maxLoss: idea.maxLoss,
    expectedReward: idea.expectedReward,
    exitPlan: idea.exitPlan,
    spyTrend: idea.spyTrend,
    qqqTrend: idea.qqqTrend,
    vixCondition: idea.vixCondition,
    marketBreadth: idea.marketBreadth,
    macroRisk: idea.macroRisk,
    trend: idea.trend,
    priceVs20MA: idea.priceVs20MA,
    priceVs50MA: idea.priceVs50MA,
    rsiCondition: idea.rsiCondition,
    volumeCondition: idea.volumeCondition,
    supportResistanceQuality: idea.supportResistanceQuality,
    bidAskSpreadPercent: idea.bidAskSpreadPercent,
    optionVolume: idea.optionVolume,
    openInterest: idea.openInterest,
    daysToExpiration: idea.daysToExpiration,
    impliedVolatilityRank: idea.impliedVolatilityRank,
    premiumAsPercentOfPortfolio: idea.premiumAsPercentOfPortfolio,
    isChasing: idea.isChasing,
    optionLegs: idea.optionLegs?.map((leg) => ({
      symbol: leg.symbol,
      underlying: leg.underlying,
      optionType: leg.optionType === "put" ? "put" : "call",
      side: leg.side === "short" ? "short" : "long",
      quantity: leg.quantity,
      strike: leg.strike,
      expirationDate: leg.expirationDate,
      bid: leg.bid,
      ask: leg.ask,
      mid: leg.mid,
      spreadPercent: leg.spreadPercent,
      impliedVol: leg.impliedVol,
      ivRank: leg.ivRank,
      delta: leg.delta,
      gamma: leg.gamma,
      theta: leg.theta,
      vega: leg.vega,
      rho: leg.rho,
      openInterest: leg.openInterest,
      volume: leg.volume,
      dte: leg.dte
    }))
  };
}
